controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SendMail;

use app\models\SignupForm;
use app\models\User;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {   
       /*$auth = Yii::$app->authManager;

        // add "createPost" permission
        $createPost = $auth->createPermission('createPost');
        $createPost->description = 'Create a post';
        $auth->add($createPost);

        // add "updatePost" permission
        $updatePost = $auth->createPermission('updatePost');
        $updatePost->description = 'Update post';
        $auth->add($updatePost);

        // add "author" role and give this role the "createPost" permission
        $author = $auth->createRole('author');
        $auth->add($author);
        $auth->addChild($author, $createPost);

        // add the rule
        $rule = new \app\rbac\AuthorRule;
        $auth->add($rule);

        // add the "updateOwnPost" permission and associate the rule with it.
        $updateOwnPost = $auth->createPermission('updateOwnPost');
        $updateOwnPost->description = 'Update own post';
        $updateOwnPost->ruleName = $rule->name;
        $auth->add($updateOwnPost);

        // "updateOwnPost" will be used from "updatePost"
        $auth->addChild($updateOwnPost, $updatePost);

        // allow "author" to update their own posts
        $auth->addChild($author, $updateOwnPost);


        // add "admin" role and give this role the "updatePost" permission
        // as well as the permissions of the "author" role
        $admin = $auth->createRole('admin');
        $auth->add($admin);
        $auth->addChild($admin, $updatePost);
        $auth->addChild($admin, $author);

        // Assign roles to users. 1 and 2 are IDs returned by IdentityInterface::getId()
        // usually implemented in your User model.
        $auth->assign($author, 2);
        $auth->assign($admin, 1);
        */


        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('/document');//return $this->goBack();
        }

        $registered = false;

        $model2 = new SignupForm();
        if ($model2->load(Yii::$app->request->post()) && $model2->uniqUsername() && $model2->uniqEmail()
            ) {
            $user = new User();
            $user->username = $model2->username;

            $user->name_contr = $model2->name_contr;
            $user->kpp = $model2->kpp;
            $user->ogrn = $model2->ogrn;
            $user->gen_director = $model2->gen_director;
            $user->phone = $model2->phone;
            $user->ur_adress = $model2->ur_adress;
            $user->fak_adress = $model2->fak_adress;
          
            $user->email = $model2->email;
            $user->money = 10;
            $password = rand(1,1000) . rand(1,1000) . rand(1,1000) . rand(1,1000);
            $user->password = $user->setPassword($password);
            $user->save(false);

            $auth = Yii::$app->authManager;
            $authorRole = $auth->getRole('author');
            $auth->assign($authorRole, $user->getId());

            $contact = new SendMail();
            $contact->name = 'Biznen';
            $contact->email = Yii::$app->params['adminEmail'];
            $contact->subject = 'Вы создали учетную запись на Biznen.com!';
            $contact->body = \Yii::$app->view->renderFile('@app/views/user/_signupMail.php', [
                'password' => $password, 
                ]);
            $registered = true;
            $contact->contact($model2->email);

            //return $user;
            return $this->render('login', [
                'model' => $model,
                'model2' => $model2,
                'registered' => $registered,
            ]);
        }

        return $this->render('login', [
            'model' => $model,
            'model2' => $model2,
            'registered' => false,
        ]);
    }

    public function actionMess(){
        $contact = new SendMail();
        $contact->name = 'lqwerty';
        $contact->email = 'my@mail.ru';
        $contact->subject = 'from site';
        $contact->body = 'your password is';
        var_dump($contact->contact(Yii::$app->params['adminEmail']));

    } 

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionHowit()
    {
        return $this->render('how_it');
    }

}

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Контакты';
//$this->params['breadcrumbs'][] = $this->title;
?>

<?php echo \Yii::$app->view->renderFile('@app/views/site/header.php'); ?>

<div class="container site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
           Спасибо за ваше обращение, мы ответим вам как только сможем.
        </div>

        <p>
            <!--Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.-->
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>
    <br>
    <h4>Тел. В Москве +7(499)343-06-30</h4>
    <br>
        <p>
            Если у вас есть вопросы вы можете написать нам через форму ниже.
        </p>
        <p>Если вы забыли пароль, то вы можете написать нам, мы отправим на ваш электронный адрес временный пароль,</p>
        <p>который вы сможете поменять в личном кабинете, все это сделано в целях безопасности</p>
        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

<?php echo \Yii::$app->view->renderFile('@app/views/site/footer.php'); ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/footer.php
        

        <div class="container"><div class="scrollTop"><span class="glyphicon glyphicon-menu-up"></span></div></div>
</div>



<footer class="footer">


    <div class="container">
        <div class="row"> 

            <div class="col-xs-12 col-md-12"> 
            	<div class="row">
            		<div class="col-md-6 col-lg-6 col-sm-12">
            			<a class="navbar-brand" href="/" style="padding: 0px;">
            				<img src="/img/ic6.png"><span>
            				<p style="color: white;">Biznen</p>
            				<p>Сервис выставления счетов</p></span>
            			</a>
            		</div>
            		<div class="col-md-6 col-lg-6 col-sm-12 footer-social">
						    <span style="font-size: 23px;margin: -3px 0px;">

    <a href="#"><span class="icomoon icomoon-vk-with-circle"></span></a>
    <a href="#"><span class="icomoon icomoon-facebook-with-circle"></span></a>
    <a href="#"><span class="icomoon icomoon-linkedin-with-circle"></span></a>
</span>
						    <br>
				            <a><span class="glyphicon glyphicon glyphicon-earphone"></span> +7(499)343-06-30</a>
				            <a><span class="glyphicon glyphicon glyphicon-envelope"></span> info@biznen.com</a>
            		</div>
            	</div>
            </div> 
            <br>
            <hr class="col-xs-12 col-md-12" style="color:#8B959B;">
            <div class="col-xs-12 col-md-12 footer-copyright"> 
                <p><cite>© <?= date('Y') ?> Biznen. Все права защищены.</cite></p> 
            </div> 

        </div>
    </div>
</footer>

<div class="container">

views/site/header.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

$this->registerCssFile('/css/helper.css');

?>

</div>
<div class="showfoto"></div>

<div class="wrap">

    

<?php

    $this->registerJs("
        $('.scrollTop').click(function(){
            $('body,html').animate({ scrollTop : 0 }, 500);
        });

        var bodyHeight = document.body.scrollHeight, pageScroll = 0;
        window.onscroll = function(){ 
            pageScroll = $(window).scrollTop();
            var shNavbar = $('.sh-navbar').offset();
            shNavbar = shNavbar.top + $('.sh-navbar').height();
            if ($(window).scrollTop() > 100) $('.scrollTop').show(); else $('.scrollTop').hide();
            if ($(window).scrollTop() > shNavbar && bodyHeight > window.innerHeight + shNavbar +100) { 
                $('.sh-navbar-fixed').addClass('navbar-fixed-top');
                $('.sh-navbar').css({ marginBottom : $('.sh-navbar-fixed').height() });
            } else { 
                $('.sh-navbar-fixed').removeClass('navbar-fixed-top');
                $('.sh-navbar').css({ marginBottom : 0 });
            }
        }"
        );

    NavBar::begin([
        'options' => [
            'class' => 'navbar-inverse sh-navbar',
        ],
    ]);

    ?>
<ul class="navbar-nav navbar-left nav">

            <li><a><span class="glyphicon glyphicon glyphicon-earphone"></span> +7(499)343-06-30</a></li>
            <li><a><span class="glyphicon glyphicon glyphicon-envelope"></span> info@biznen.com</a></li>
</ul>

<ul class="navbar-nav navbar-right nav" style="font-size: 23px;margin: -3px 0px;">

    <li><a href="#"><span class="icomoon icomoon-vk-with-circle"></span></a></li>
    <li><a href="#"><span class="icomoon icomoon-facebook-with-circle"></span></a></li>
    <li><a href="#"><span class="icomoon icomoon-linkedin-with-circle"></span></a></li>

</ul>
    <?php
    NavBar::end();

    NavBar::begin([
        'brandLabel' => '<img src="/img/ic6.png" /><span><p>Biznen</p><p>Сервис выставления счетов</p></span>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse dl-nav sh-navbar-fixed',
        ],
    ]);


    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'О ПРОЕКТЕ', 'url' => ['/site/howit']],
            ['label' => 'ДЕМО РЕЖИМ', 'url' => ['/site/howit']],
            ['label' => 'ПОДДЕРЖКА', 'url' => ['/site/howit']],
            ['label' => 'КОНТАКТЫ', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'ВХОД/РЕГИСТРАЦИЯ', 'url' => ['/site/login']]
            ) : (
                '
                <ul class="navbar-nav navbar-left nav hidden-xs">
                        
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-user"></span>
                        <span class="caret"></span>
                    </a>
                      <ul class="dropdown-menu">
                        <li><a href="/profile">Профиль ' . Yii::$app->user->identity->username . '</a></li>
                        <li><a href="/document">Документооборот</a></li>
                        <li role="separator" class="divider"></li>
                        <li style="background: rgb(27, 39, 50) none repeat scroll 0% 0%;">'
                            . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                            . Html::submitButton(
                                '<span class="glyphicon glyphicon-log-out"></span> Выход (' . Yii::$app->user->identity->username . ')',
                                ['class' => 'btn btn-link']
                            ) 
                            . Html::endForm() . '</li>
                      </ul>
                    </li>
                    
                </ul>

                <li class="hidden-sm hidden-md hidden-lg"><a href="/profile">Профиль ' . Yii::$app->user->identity->username . '</a></li>
                <li class="hidden-sm hidden-md hidden-lg"><a href="/document">Документооборот</a></li>
                <li class="hidden-sm hidden-md hidden-lg" role="separator" class="divider"></li>
                <li class="hidden-sm hidden-md hidden-lg" style="background: rgb(27, 39, 50) none repeat scroll 0% 0%;">'
                    . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                    . Html::submitButton(
                        '<span class="glyphicon glyphicon-log-out"></span> Выход (' . Yii::$app->user->identity->username . ')',
                        ['class' => 'btn btn-link']
                    ) 
                    . Html::endForm() . '</li>
                '
            ),
            /*Yii::$app->user->isGuest ? (
                        ['label' => 'Регистрация', 'url' => ['site/signup'], 'options' => ['class' => 'dl-register'] ]
                    ) : ( '' ),*/
        ],
    ]);
    NavBar::end();
    ?>

        <?= Breadcrumbs::widget([
            'homeLink'=>[ 'label' => 'Главная', 'url' => '/', ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>

views/site/userfooter.php
<footer class="footer">


        <div class="row"> 

            <div class="col-xs-12 col-md-6 footer-copyright"> 
                <p><cite>BIZNEN © <?= date('Y') ?>. Все права защищены.</cite></p> 
            </div> 

        </div>
</footer>


            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->












<div class="container">

views/site/userheader.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;


$this->registerJs("

    if ($.session.get('toggled') == 'true'){
        $('#wrapper').toggleClass('toggled-2');    
    }


 
$('#menu-toggle').click(function(e) {
        e.preventDefault();
        $('#wrapper').toggleClass('toggled');
    });
     $('#menu-toggle-2').click(function(e) {
        e.preventDefault();
        $('#wrapper').toggleClass('toggled-2');
        $('#menu ul').hide();
        if ($.session.get('toggled') == 'true') $.session.set('toggled', false); else $.session.set('toggled', 'true');
    });

     /*function initMenu() {
      $('#menu ul').hide();
      $('#menu ul').children('.current').parent().show();
      //$('#menu ul:first').show();
      $('#menu li a').click(
        function() {
          var checkElement = $(this).next();
          if((checkElement.is('ul')) && (checkElement.is(':visible'))) {
            return false;
            }
          if((checkElement.is('ul')) && (!checkElement.is(':visible'))) {
            $('#menu ul:visible').slideUp('normal');
            checkElement.slideDown('normal');
            return false;
            }
          }
        );
      }
    $(document).ready(function() {initMenu();});*/

    ");
$this->registerJsFile('/js/jquery.session.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('/js/script.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerCssFile('/css/userpage.css');

?>


</div>

<div class="showfoto"></div>


    <?php

        NavBar::begin([
            'brandLabel' => '
                    
                    <img src="/img/ic6.png" /><span><p>Biznen</p><p>Сервис выставления счетов</p></span>
                    </a>
                    <a>
                    <button type="button" class="left-btn navbar-toggle" data-toggle="collapse" id="menu-toggle">
                      <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                    </button>
                    ',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-default navbar-fixed-top no-margin user-nav',
            ],
            'innerContainerOptions' => ['class' => 'container-fluid'],
        ]);

    ?>

                    <ul class="nav navbar-nav nav-site hidden-xs">
                        <li class="active"><button class="left-btn navbar-toggle collapse in" data-toggle="collapse" id="menu-toggle-2"> 
                            <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                        </button></li>
                    </ul>


    <?php

        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-left'],
            'items' => [
                   '
                    <ul class="navbar-nav navbar-left nav">
                            
                            <li><a href="#"><span class="icon-border icon-transparent icomoon icomoon-newspaper"></span></a></li>
                            <li><a href="#"><span class="icon-border icon-transparent glyphicon glyphicon-envelope"></span></a></li>
                            
                        </ul>
                    '
            ],
        ]);

        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => [
                //['label' => 'Как это работает', 'url' => ['/site/howit']],
                Yii::$app->user->isGuest ? (
                    ['label' => 'Войти', 'url' => ['/site/login']]
                ) : (
                    '
                    <ul class="navbar-nav navbar-left nav hidden-xs">
                            
                        <li><a href="#"><span class="icon-border icon-transparent icomoon icomoon-book"></span></a></li>
                        <li><a href="#"><span class="icon-border icon-transparent glyphicon glyphicon-question-sign"></span></a></li>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="icon-border glyphicon glyphicon-user"></span> ' . Yii::$app->user->identity->username . ' <span class="caret"></span>
                        </a>
                          <ul class="dropdown-menu">
                            <li><a href="/profile">Профиль ' . Yii::$app->user->identity->username . '</a></li>
                            <li><a href="/document">Документооборот</a></li>
                            <li role="separator" class="divider"></li>
                            <li style="background: rgb(27, 39, 50) none repeat scroll 0% 0%;">'
                                . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                                . Html::submitButton(
                                    '<span class="glyphicon glyphicon-log-out"></span> Выход (' . Yii::$app->user->identity->username . ')',
                                    ['class' => 'btn btn-link']
                                ) 
                                . Html::endForm() . '</li>
                          </ul>
                        </li>
                        
                    </ul>
                    <li class="hidden-sm hidden-md hidden-lg"><a href="/profile">Профиль ' . Yii::$app->user->identity->username . '</a></li>
                    <li class="hidden-sm hidden-md hidden-lg"><a href="/document">Документооборот</a></li>
                    <li class="hidden-sm hidden-md hidden-lg" role="separator" class="divider"></li>
                    <li class="hidden-sm hidden-md hidden-lg" style="background: rgb(27, 39, 50) none repeat scroll 0% 0%;">'
                        . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                        . Html::submitButton(
                            '<span class="glyphicon glyphicon-log-out"></span> Выход (' . Yii::$app->user->identity->username . ')',
                            ['class' => 'btn btn-link']
                        ) 
                        . Html::endForm() . '</li>
                    '
                ),
                Yii::$app->user->isGuest ? (
                            ['label' => 'Регистрация', 'url' => ['site/signup'], 'options' => ['class' => 'dl-register'] ]
                        ) : ( '' ),
            ],
        ]);
        NavBar::end();
    ?>




    <div class="toggled-2" id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav nav-pills nav-stacked" id="menu">

                <li <?php if ($_SERVER['REQUEST_URI'] == "/schet/create") echo 'class="active"'; ?> >
                    <a href="/schet/create"><span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-news fa-stack-1x "></i></span> Выставить счет</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/schet") echo 'class="active"'; ?> >
                    <a href="/schet"><span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-files-empty fa-stack-1x "></i></span> Счета</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/contragent") echo 'class="active"'; ?> >
                    <a href="/contragent"><span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-office fa-stack-1x"></i></span> Контрагенты</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/document") echo 'class="active"'; ?> >
                    <a href="/document"> <span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-book-bookmark fa-stack-1x "></i></span> Документооборот</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/act/create") echo 'class="active"'; ?> >
                    <a href="/act/create"><span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-document-text fa-stack-1x "></i></span> Акты</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/torg12/create") echo 'class="active"'; ?> >
                    <a href="/torg12/create"><span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-newspaper3 fa-stack-1x "></i></span> Товарные накладные</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/schet-faktura/create") echo 'class="active"'; ?> >
                    <a href="/schet-faktura/create"><span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-file-text2 fa-stack-1x "></i></span> Счета-фактуры</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/platej-poruch/create") echo 'class="active"'; ?> >
                    <a href="/platej-poruch/create"><span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-note-list fa-stack-1x "></i></span> Платежное поручение</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/upd/create") echo 'class="active"'; ?> >
                    <a href="/upd/create"><span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-notebook-list fa-stack-1x "></i></span> УПД</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/user/file") echo 'class="active"'; ?> >
                    <a href="/user/file"><span class="fa-stack fa-lg pull-left"><i class="glyphicon glyphicon-pencil fa-stack-1x "></i></span> Подпись и печать</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/export") echo 'class="active"'; ?> >
                    <a href="/export"><span class="fa-stack fa-lg pull-left"><i class="glyphicon glyphicon-new-window fa-stack-1x "></i></span> Экспорт данных</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/statistic") echo 'class="active"'; ?> >
                    <a href="/statistic"><span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-stats-dots fa-stack-1x "></i></span> Статистика</a>
                </li>
                <li <?php if ($_SERVER['REQUEST_URI'] == "/balance") echo 'class="active"'; ?> >
                    <a href="/balance"><span class="fa-stack fa-lg pull-left"><i class="icomoon icomoon-banknote fa-stack-1x "></i></span> Выбор тарифного плана</a>
                </li>
            <div class="proba">У Вас пробная версия сервиса, осталось 30 дней.</div>

            </ul>
        </div><!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid xyz">
 

        <?= Breadcrumbs::widget([
            'homeLink'=>[ 'label' => 'Главная', 'url' => '/', ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>