models/Document.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "document".
 *
 * @property integer $id
 * @property string $identify
 * @property string $company
 * @property string $date
 */
class Document extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'document';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['prodaves_id', 'pokupatel_id', 'pechatforma', 'nds', 'currency', 'pay_for', 'byDogovor'], 'required', 'message'=>'Необходимо заполнить'],
            [['prodaves_id', 'pokupatel_id'], 'integer', 'message'=>'Необходимо ввести строку'],
            [['pay_for', 'byDogovor'], 'string', 'max'=>300, 'min'=>2, 'tooLong' => 'Необходимо ввести меньше символов', 'tooShort'=>'Необходимо ввести больше символов'],
            [['nds', 'currency', 'pechatforma'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'prodaves_id' => 'Укажите продавца',
            'pokupatel_id' => 'Укажите покупателя',
            'pay_for' => 'Оплата за ...',
            'byDogovor' => '...по Договору (номер, дата)',
            'pechatforma' => 'Печатная форма счета',
            'nds' => 'НДС',
            'currency' => 'Валюта',
        ];
    }

    public function getSchet()
    {
        return $this->hasOne(Schet::className(), ['id_document' => 'id']);
    }

    public function getTorg12()
    {
        return $this->hasOne(Torg12::className(), ['id_document' => 'id']);
    }

    public function getAct()
    {
        return $this->hasOne(Act::className(), ['id_document' => 'id']);
    }

    public function getSchetFaktura()
    {
        return $this->hasOne(SchetFaktura::className(), ['id_document' => 'id']);
    }

    public function getPlatejPoruch()
    {
        return $this->hasOne(PlatejPoruch::className(), ['id_document' => 'id']);
    }

    public function getUpd()
    {
        return $this->hasOne(Upd::className(), ['id_document' => 'id']);
    }

    public function getProdaves()
    {
        return $this->hasOne(Contragent::className(), ['id' => 'prodaves_id']);
    }

    public function getPokupatel()
    {
        return $this->hasOne(Contragent::className(), ['id' => 'pokupatel_id']);
    }
}

controllers/DocumentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Document;
use app\models\DocumentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * DocumentController implements the CRUD actions for Document model.
 */
class DocumentController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'update', 'view', 'delete', 'create', 'statistic', 'export'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['index', 'update', 'view', 'delete', 'create', 'statistic', 'export'],
                        'allow' => true,
                        'roles' => ['author'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Document models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DocumentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Document model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionStatistic()
    {
        return $this->render('statistic');
    }


    public function actionExport()
    {
        return $this->render('export');
    }

    /**
     * Creates a new Document model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Document();
        $model->createdBy = Yii::$app->user->getId();


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Document model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Document model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        if ($model->schet != null) {

            if ($model->schet->services !== null) {
              foreach ($model->schet->services as $current) {
                $current->delete();
              }
            }

            $model->schet->delete();
        }
        if ($model->torg12 != null) {

            if ($model->torg12->services !== null) {
              foreach ($model->torg12->services as $current) {
                $current->delete();
              }
            }
            
            $model->torg12->delete();
        }
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Document model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Document the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Document::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/document/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Document */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="document-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'identify')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'company')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/document/_list.php
<?php

use yii\helpers\Html;

$schetActive = "";
$schetHasData = false;
$schetClass = "mylist";

if ($model->schet != null) {
        if ($model->torg12 != null || $model->act != null || $model->schetFaktura != null) { $schetHasData = true; $schetClass = "mylistIn"; }
?>
<div class="mylist" onclick="selectRow(this, 'document')">
        <input type="hidden" value="schet" class="docType" />
        <input type="hidden" value='"id" : "<?= $model->id ?>", "type" : "schet", 
        "torg12" : "<?php if ($model->torg12 == null) echo "empty"; ?>", 
        "act" : "<?php if ($model->act == null) echo "empty"; ?>", 
        "schetFaktura" : "<?php if ($model->schetFaktura == null) echo "empty"; ?>", 
        "platejPoruch" : "<?php if ($model->platejPoruch == null) echo "empty"; ?>", 
        "upd" : "<?php if ($model->upd == null) echo "empty" ?>"' class="docId" />
        <input type="hidden" value="<?= $model->id ?>" class="id" />
        <input type="hidden" value="<?= $model->schet->id ?>" class="idself" />
        <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->schet->date ?></div>
        <div class="col-lg-1 col-md-2 col-sm-2">
                <?php echo  $model->schet->id; if ($schetHasData) { ?>
                <a class="collapseBtS<?= $model->schet->id?>" role="button" data-toggle="collapse" href="#collapseFieldS<?= $model->schet->id?>" 
                        aria-expanded="false" aria-controls="collapseFieldS<?= $model->schet->id?>">
                      <span class="icon-border icon-blue glyphicon glyphicon-menu-down"></span> 
                </a> 
                <?php } ?>
        </div>
        <div class="col-lg-1 col-md-2 col-sm-2">Счет</div>
        <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->name_contr ?></div>
        <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->pay_for ?></div>
        <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->gen_director ?></div>
        <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->schet->sum ?></div>
</div>


<?php
if ($schetHasData) {
        $this->registerJs('

                $("#collapseFieldS'.$model->schet->id.'").on("hidden.bs.collapse", function () {
                        $(".collapseBtS'.$model->schet->id.'").find("span").removeClass("glyphicon-menu-up").addClass("glyphicon-menu-down");
                });

                $("#collapseFieldS'.$model->schet->id.'").on("shown.bs.collapse", function () {
                        $(".collapseBtS'.$model->schet->id.'").find("span").removeClass("glyphicon-menu-down").addClass("glyphicon-menu-up");
                });

        ');

}

if ($schetHasData) echo '<div class="collapse"  id="collapseFieldS'.$model->schet->id.'">';
} 

if ($model->torg12 != null) {
?>

<div class="<?=$schetClass?>" onclick="selectRow(this, 'document')">
                <input type="hidden" value="torg12" class="docType" />
                <input type="hidden" value="<?= $model->id ?>" class="id" />
                <input type="hidden" value="<?= $model->torg12->id ?>" class="idself" />
                <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->torg12->date ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2"><?=$model->torg12->id ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2">Торг 12</div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->name_contr ?></div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->pay_for ?></div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->gen_director ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->torg12->sum ?></div>
</div>
<?php } 

if ($model->act != null) {
?>
<div class="<?=$schetClass?>" onclick="selectRow(this, 'document')">
                <input type="hidden" value="act" class="docType" />
                <input type="hidden" value="<?= $model->id ?>" class="id" />
                <input type="hidden" value="<?= $model->act->id ?>" class="idself" />
                <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->act->date ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2"><?=$model->act->id ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2">Акт</div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->name_contr ?></div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->pay_for ?></div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->gen_director ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->act->sum ?></div>
</div>
<?php } 

if ($model->schetFaktura != null) {
?>
<div class="<?=$schetClass?>" onclick="selectRow(this, 'document')">
                <input type="hidden" value="schetFaktura" class="docType" />
                <input type="hidden" value="<?= $model->id ?>" class="id" />
                <input type="hidden" value="<?= $model->schetFaktura->id ?>" class="idself" />
                <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->schetFaktura->date ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2"><?=$model->schetFaktura->id ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2">Счет фактура</div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->name_contr ?></div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->pay_for ?></div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->gen_director ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->schetFaktura->sum ?></div>
</div>
<?php } 

if ($model->platejPoruch != null) {
?>
<div class="<?=$schetClass?>" onclick="selectRow(this, 'document')">
                <input type="hidden" value="platejPoruch" class="docType" />
                <input type="hidden" value="<?= $model->id ?>" class="id" />
                <input type="hidden" value="<?= $model->platejPoruch->id ?>" class="idself" />
                <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->platejPoruch->date ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2"><?=$model->platejPoruch->id ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2">Платежное поручение</div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->name_contr ?></div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->pay_for ?></div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->gen_director ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->platejPoruch->sum ?></div>
</div>
<?php } 

if ($model->upd != null) {
?>
<div class="<?=$schetClass?>" onclick="selectRow(this, 'document')">
                <input type="hidden" value="upd" class="docType" />
                <input type="hidden" value="<?= $model->id ?>" class="id" />
                <input type="hidden" value="<?= $model->upd->id ?>" class="idself" />
                <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->upd->date ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2"><?=$model->upd->id ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2">УПД</div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->name_contr ?></div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->pay_for ?></div>
                <div class="col-lg-2 col-md-4 col-sm-4"><?= $model->prodaves->gen_director ?></div>
                <div class="col-lg-1 col-md-2 col-sm-2"><?= $model->upd->sum ?></div>
</div>
<?php } 

if ($schetHasData) echo '</div>';
?>

views/document/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

$this->registerJsFile('/js/bootstrap-datepicker.js', ['depends' => [\yii\web\JqueryAsset::className()]]);

$this->registerCssFile('/css/bootstrap-datepicker.css');

$this->registerJs('
    $(document).ready(function(){
        $("#catout").on("pjax:end", function(){
            $.pjax.reload({ container : "#catin" });
        });

        $(".delete").click(function(event){
            if ($(this).attr("href") == "" || $(this).attr("href") == "#") return false;
            else $(this).attr("data-confirm", "Are you sure you want to delete this item?")
        });

    });

//0
$("#collapseField0").on("hidden.bs.collapse", function () {
  $(".collapseBt0").find("span").removeClass("glyphicon-menu-up").addClass("glyphicon-menu-down");
});

$("#collapseField0").on("shown.bs.collapse", function () {
  $(".collapseBt0").find("span").removeClass("glyphicon-menu-down").addClass("glyphicon-menu-up");
});

    ');
?>

<?php Pjax::begin(['id' => 'catout']); ?>

<div class="collapseBtF">
    <a class="collapseBt0" role="button" data-toggle="collapse" href="#collapseField0" aria-expanded="false" aria-controls="collapseField0">
      <span class="icon-border icon-blue glyphicon glyphicon-menu-up"></span> 
    </a> 
    <span class="icomoon icomoon-filter"></span> <span class="icText">Фильтр</span>
</div>
<div class="row myrow collapse in"  id="collapseField0">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => ['data-pjax'=>true, 'onchange' => "var container = $(this).closest('[data-pjax-container]');    $.pjax.submit(event, container)"],
    ]); ?>

        <div class="col-lg-2 col-md-2 col-sm-4">
            <?= $form->field($model, 'schetinn')->textInput(['autofocus' => true, 'placeholder' => 'По номеру, товара, оплата за...'])->label('Поиск счета') ?>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-4">
            <?= $form->field($model, 'prodaves')->textInput(['autofocus' => true, 'placeholder' => 'Поиск по наименованию, ИНН'])->label('Продавец') ?>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-4">
            <?= $form->field($model, 'pokupatel')->textInput(['autofocus' => true, 'placeholder' => 'Поиск по наименованию, ИНН'])->label('Покупатель') ?>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-4">
            <?= $form->field($model, 'dateFrom')->textInput(['autofocus' => true, 'placeholder' => 'Начальная дата'])->label('Период, с...') ?>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-4">
            <?= $form->field($model, 'dateTo')->textInput(['autofocus' => true, 'placeholder' => 'Конечная дата'])->label('по...') ?>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-1 col-md-2 col-sm-2 col-xs-4 margint20">
        <?= Html::submitButton('<span class="glyphicon glyphicon-search"></span> <span class="icTextBtn">Поиск</span> ', ['class' => 'btn linkBtn']) ?>
    </div>


</div>

<div class="row myrow up">
    <div class="col-lg-2 col-md-4 col-sm-4">
        <?php $form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
            'options' => ['data-pjax'=>true, 'onchange' => "var container = $(this).closest('[data-pjax-container]');    $.pjax.submit(event, container)"],
        ]); ?>


        <?= $form->field($model, 'pokupatel')->textInput(['autofocus' => true, 'placeholder' => 'поиск...'])->label(false) ?>

        <?php ActiveForm::end(); ?>

    </div>
    <div class="col-lg-1 col-md-2 col-sm-2 col-xs-4">
        <a class="btn linkBtn createDoc" data-toggle="modal" data-target="#documentModal" data-whatever="">
            <span class="glyphicon glyphicon-print"></span> <span class="icTextBtn">Новый</span>
        </a>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> <span class="icTextBtn">Редактировать</span>', ['#'], ['class' => 'btn linkBtn edit']) ?>
    </div>
    <div class="col-lg-1 col-md-2 col-sm-2 col-xs-4">
        <a class="btn linkBtn printBig" data-toggle="modal" data-target="#schetModal">
            <span class="glyphicon glyphicon-print"></span> <span class="icTextBtn">Печать</span>
        </a>
    </div>
    <div class="col-lg-1 col-md-2 col-sm-2 col-xs-4">
        <a class="btn linkBtn saveBig" data-toggle="modal" data-target="#schetModalEmail">
            <span class="glyphicon glyphicon-floppy-disk"></span> <span class="icTextBtn">E-mail</span>
        </a>
    </div>
    <div class="col-lg-1 col-md-2 col-sm-2 col-xs-4">
        <a href="#" class="btn linkBtn delete" title="Delete" aria-label="Delete" data-method="post" data-pjax="0">
            <span class="glyphicon glyphicon-trash"></span> <span class="icTextBtn">Удалить</span>
        </a>
    </div>



</div>


<?php Pjax::end(); ?>

views/document/create.php
<?php

use yii\helpers\Html;

$this->title = 'Create Document';
$this->params['breadcrumbs'][] = ['label' => 'Documents', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php echo \Yii::$app->view->renderFile('@app/views/site/userheader.php'); ?>

<div class="document-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>


<?php echo \Yii::$app->view->renderFile('@app/views/site/userfooter.php'); ?>

views/document/export.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;


$this->title = "Выгрузить данные";
?>

<?php echo \Yii::$app->view->renderFile('@app/views/site/userheader.php'); ?>

<div class="contragent-view">

    <h3><?= Html::encode($this->title) ?></h3>


</div>

<?php echo \Yii::$app->view->renderFile('@app/views/site/userfooter.php'); ?>

views/document/statistic.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;


$this->title = "Статистика";

$this->registerJsFile('js/Chart.js');
$this->registerJs('
		var randomScalingFactor = function(){ return Math.round(Math.random()*100)};
		var lineChartData = {
			labels : ["January","February","March","April","May","June","July"],
			datasets : [
				{
					label: "My First dataset",
					fillColor : "rgba(220,220,220,0.2)",
					strokeColor : "rgba(220,220,220,1)",
					pointColor : "rgba(220,220,220,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(220,220,220,1)",
					data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
				},
				{
					label: "My Second dataset",
					fillColor : "rgba(151,187,205,0.2)",
					strokeColor : "rgba(151,187,205,1)",
					pointColor : "rgba(151,187,205,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
				}
			]

		}

	window.onload = function(){
		var ctx = document.getElementById("canvas").getContext("2d");
		window.myLine = new Chart(ctx).Line(lineChartData, {
			responsive: true
		});
	}
	');


$this->registerCss("
.statistic {
	padding: 20px;
background: #FFF;
border: 1px solid #e0e0e0;
margin-bottom: 25px;
}
	");
?>

<?php echo \Yii::$app->view->renderFile('@app/views/site/userheader.php'); ?>

<div class="contragent-view row">

    <h3><?= Html::encode($this->title) ?></h3>

		<div class="col-lg-6 col-md-6 col-sm-12">
			<div class="statistic">
				<div>
					<canvas id="canvas" height="450" width="600"></canvas>
				</div>
			</div>
		</div>
<div class="clear"></div>


</div>

<?php echo \Yii::$app->view->renderFile('@app/views/site/userfooter.php'); ?>

views/document/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Document */

$this->title = 'Update Document: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Documents', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>

<?php echo \Yii::$app->view->renderFile('@app/views/site/userheader.php'); ?>

<div class="document-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>


<?php echo \Yii::$app->view->renderFile('@app/views/site/userfooter.php'); ?>

views/document/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Document */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Documents', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php echo \Yii::$app->view->renderFile('@app/views/site/userheader.php'); ?>

<div class="document-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'identify',
            'company',
            'date',
        ],
    ]) ?>

</div>


<?php echo \Yii::$app->view->renderFile('@app/views/site/userfooter.php'); ?>